"use client";

import React, { useState } from "react";
import { StartupDeal } from "@/types/startup";
import { FileText, Copy, Download, Share2, Sparkles, Check, ArrowLeft } from "lucide-react";
import { cn } from "@/lib/utils";

interface MemoEditorProps {
  startup: StartupDeal;
  onBack: () => void;
}

export const MemoEditor: React.FC<MemoEditorProps> = ({ startup, onBack }) => {
  const [copied, setCopied] = useState(false);
  const [memoText, setMemoText] = useState(
    startup.memoMarkdown ||
      `# Investment Memo: ${startup.name}

## Executive Summary
${startup.name} is solving critical challenges in ${startup.sector} with their core product: "${startup.tagline}".

## Thesis Alignment Analysis
- **Pando Root Match Score**: ${startup.thesisMatch.score}%
- **Signal Source**: ${startup.source.toUpperCase()}
- **Funding Stage**: ${startup.stage.toUpperCase()}
- **Location**: ${startup.location}

## Key Strengths
${startup.thesisMatch.pros.map((p) => `- ${p}`).join("\n")}

## Risks & Diligence Questions
${startup.thesisMatch.keyQuestions.map((q) => `- ${q}`).join("\n")}

## Recommendation
**PROCEED TO PARTNER INTERVIEW**.
`
  );

  const handleCopy = () => {
    navigator.clipboard.writeText(memoText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="rounded-2xl border border-pando-border bg-pando-card p-6 shadow-2xl max-w-4xl mx-auto">
      {/* Header Actions */}
      <div className="flex items-center justify-between border-b border-pando-border pb-4 mb-6">
        <button
          onClick={onBack}
          className="flex items-center gap-2 rounded-xl border border-pando-border bg-pando-dark px-3 py-1.5 text-xs text-pando-muted hover:text-white hover:border-emerald-500/50 transition-colors"
        >
          <ArrowLeft className="h-4 w-4" />
          <span>Back to Deal Flow</span>
        </button>

        <div className="flex items-center gap-2">
          <button
            onClick={handleCopy}
            className="flex items-center gap-1.5 rounded-xl border border-pando-border bg-pando-dark px-3.5 py-2 text-xs font-semibold text-white hover:border-emerald-500/40 transition-colors"
          >
            {copied ? <Check className="h-4 w-4 text-emerald-400" /> : <Copy className="h-4 w-4 text-pando-muted" />}
            <span>{copied ? "Copied!" : "Copy Markdown"}</span>
          </button>

          <button
            onClick={() => window.print()}
            className="flex items-center gap-1.5 rounded-xl bg-gradient-to-r from-emerald-500 to-teal-600 hover:from-emerald-400 hover:to-teal-500 px-4 py-2 text-xs font-bold text-white shadow-glow transition-all"
          >
            <Download className="h-4 w-4" />
            <span>Export PDF</span>
          </button>
        </div>
      </div>

      {/* Editor Box */}
      <div className="space-y-4">
        <div className="flex items-center gap-3">
          <img src={startup.logo} alt={startup.name} className="h-10 w-10 rounded-xl object-cover border border-pando-border" />
          <div>
            <h1 className="text-xl font-bold text-white">{startup.name} — Investment Memo</h1>
            <p className="text-xs font-mono text-emerald-400">Generated by Pando AI Agent Engine</p>
          </div>
        </div>

        <textarea
          value={memoText}
          onChange={(e) => setMemoText(e.target.value)}
          rows={18}
          className="w-full rounded-2xl border border-pando-border bg-pando-dark/80 p-5 font-mono text-xs text-slate-200 leading-relaxed focus:border-emerald-500/50 focus:outline-none resize-y"
        />
      </div>
    </div>
  );
};
